image: atlassian/default-image:3

# Workflow Configuration

pipelines:
  default:
    - parallel:
      - step:
          name: Validate with AWS
          image: amazon/aws-cli:2.3.3
          script:
            # More details https://docs.aws.amazon.com/cli/latest/reference/cloudformation/validate-template.html
            - aws cloudformation validate-template --template-body file://bbbackup_cf.json
      - step:
          name: Lint the template
          image: python:3.8
          script:
            - pip install cfn-lint
            # Validate CloudFormation yaml/json templates https://github.com/aws-cloudformation/cfn-python-lint
            - cfn-lint -I bbbackup_cf.json
  branches:
    master:
      - parallel:
        - step:
            name: Validate with AWS
            image: amazon/aws-cli:2.3.3
            script:
              - aws cloudformation validate-template --template-body file://bbbackup_cf.json
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to Production
          deployment: Production
          trigger: manual
          script:
            # Deploy your configuration as code using AWS CloudFormation.
            # See more details https://bitbucket.org/atlassian/aws-cloudformation-deploy
            - pipe: atlassian/aws-cloudformation-deploy:0.12.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                STACK_NAME: 'bbbackup'
                TEMPLATE: 'bbbackup_cf.json'
                WAIT: 'true'
                STACK_PARAMETERS: >
                  [{
                    "ParameterKey": "BitBucketUserId",
                    "ParameterValue": $BBUserId
                   },
                   {
                      "ParameterKey": "BitBucketAppPassword",
                      "ParameterValue": $BBAppPassword
                    },
                    {
                        "ParameterKey": "BitBucketTeam",
                        "ParameterValue": $BBTeam
                    },
                    {
                        "ParameterKey": "AMIID",
                        "ParameterValue": "ami-0a8b4cd432b1c3063"
                    },
                    {
                        "ParameterKey": "InstanceType",
                        "ParameterValue": t2.micro
                    },
                    {
                        "ParameterKey": "EC2KeyName",
                        "ParameterValue": "kishor-test"
                    },
                    {
                        "ParameterKey": "SSHLocation",
                        "ParameterValue": "0.0.0.0/0"
                    },
                    {
                        "ParameterKey": "SubnetID",
                        "ParameterValue": $SubnetID
                    },
                    {
                        "ParameterKey": "VPC",
                        "ParameterValue": $VPC
                    },
                    {
                        "ParameterKey": "EFSVolumeName",
                        "ParameterValue": "bbbackup"
                    },

                  }]
                CAPABILITIES: ['CAPABILITY_NAMED_IAM']